local_backend: true
backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "planning-applications"
    label: "Planning applications"
    folder: "content/planning-applications"
    slug: ""
    create: true
    extension: mdx
    format: frontmatter
    fields:
      - { label: "Application number", name: "title", widget: "string", hint: "Make sure this exactly matches the Camden application number, e.g. 2021/1000/P" }
      - { label: "Name of development", name: "name", widget: "string", hint: "Use a short title that describes this development" }
